[build]
  command = "ng build && ng run serverless-angular-workshop:serverless:production"
  publish = "dist/serverless-angular-workshop/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
